# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: check-added-large-files
            -   id: requirements-txt-fixer
            -   id: no-commit-to-branch
                args: ['--branch', 'master']

    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v5.9.3
        hooks:
            -   id: isort

    -   repo: https://github.com/psf/black
        rev: 21.7b0
        hooks:
            -   id: black
                language_version: python3
                args: ['-l 100']

    -   repo: local
        hooks:
            -   id: pydoc
                name: pydocstyle
                entry: pydocstyle
                language: python


    -   repo: local
        hooks:
            -   id: pylint
                name: pylint
                entry: pylint
                language: system
                files: \.py$
                exclude: (.*versions.*|.*_examples\.py$|setup.py)
                args: ["--rcfile=.pylintrc"]

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.910
        hooks:
            -   id: mypy
                verbose: true
                exclude: 'tests|alembic|setup.py'
                additional_dependencies:
                    - 'sqlalchemy'
                    - 'sqlalchemy2-stubs'
                    - 'types-python-dateutil'

    -   repo: local
        hooks:
            -   id: message-format
                name: message-format
                entry: .commands/pre-commit-msg-hook.sh
                language: script
                stages: [commit-msg]
                always_run: True
